# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22335d3a20b316d218291e83a97d3303ee02abb815626ffd5a431b4bf69215a82c550f5b741871089feeb55a6b88f409a93580a9e117b9daa197ac9ab5c2b603
  rabbit:
    host: localhost
    port: 5672
  base:
    blarg: true

test:
  secret_key_base: 999a6f5adf9300cb4b6541b4ed08c74b965c87fcbf744b8e56f6a1d8a31f7df6775148b707b3cad421b6ed7f4382e19699211672a771781269d1bb47d1a8413b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rabbit:
    host: localhost
    port: 5672
  base:
    blarg: true
  chef:
    url: <%= ENV["CHEF_URL"] %>
    client: <%= ENV["CHEF_CLIENT"] %>
    key: <%= ENV["CHEF_KEY"] %>
